version: '3'
services:
  psql:
    image: postgres
    container_name: "sonar-psql"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube-postgresql-data:/var/lib/postgresql/data
    ports:
      - "5440:5432"
  sonarqube:
    image: sonarqube
    container_name: "sonar-web"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://psql:5440/sonar
    ports:
      - "9010:9000"
    volumes:
      - sonarqube-conf:/opt/sonarqube/conf
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions

volumes:
   sonarqube-conf:
   sonarqube-data:
   sonarqube-extensions:
   sonarqube-postgresql-data:
